[[ch02]]
[[intro]]
== Bitcoin Explained

[[ch02_intro]]
=== Que es el Dinero?

En este capitulo quiero explicar lo que es el dinero. Es un concepto muy simple. Un niño de 10 años tendría que poder entenderlo, pero no es enseñado en la escuela. Podemos especular siglos y no llegar a una conclusión del porque pero es así. Así que vamos a explicarlo ahora.

El dinero es un medio para intercambiar valor entre dos personas. Es eso. Simple y directo. Lo complicado es explicar o entender que es 'intercambiar valor'. Valor es algo valioso para alguien. Es una cuestión subjetiva como una mercancía o un servicio.

Un ejemplo de valor seria, una bolsa de harina. El que tiene una bolsa de harina de mas quiere intercambiarla por otra cosa. Que alguien le corte el pasto en su casa. Sin embargo, hacer un trueque (es decir una bolsa de harina por una cortada de pasto) no es conveniente. Que pasa si por ejemplo, cortar el pasto es 1/100 de una bolsa de harina. Hay que hacer un trueque por 1/100 de una bolsa de harina. Y ahí empieza a verse las propiedades del valor (o el dinero).

A continuación explicamos las propiedades de 'valor'. Para intercambiar valor eficientemente necesitamos las siguientes propiedades:

- Fungible:

 > Una unidad es intercambiable con otra

- Durable:

 > No se echa a perder fácilmente. 

- Divisible:

 > Una unidad se puede dividir fácilmente

- Portable:

 > Una persona lo puede llevar fácilmente

- Aceptable:

 > Es de fácil intercambio porque es de fácil intercambio

- Escaso:

 > Hay poco y no es fácil crear mas

- Uniforme:

 > Todo el dinero que tiene la misma denominación se puede usar indistintamente

Todas estas propiedades son importantes. Por ejemplo, la sal, durante un tiempo de la historia fue usado como dinero. Si vamos a través de las propiedades podemos constatar que cumple varias de ellas. No otras y es por eso que no es usado actualmente como dinero. En el caso de la sal, por ejemplo, la propiedad durable (Que pasa si se moja?) y escasez (Hay lugares donde hay tanta sal que le quita valor) tienen problemas.

Es por eso que eventualmente las sociedades mas avanzadas gravitaron hacia el oro y la plata como valor. De nuevo, usar oro y plata servía como dinero pero tenia problemas con la propiedad portable (Como transportamos 100 kg de oro? Y como lo protegemos?).

Una manera de resolver el problema de la portabilidad fue la introducción de bancos. Instituciones que emitían unos papeles y certificaban que eran convertibles a oro o plata. Y en ese momento el problema de portabilidad fue solucionado. Pero se introdujo otro problema que fue el de la confianza. Los bancos se dieron cuenta que podían emitir mas papelitos porque la gente no reclamaba su oro en todo momento. Entonces los bancos emitieron papelitos que no estaban respaldados en oro. Es riesgoso actuar así, pero les permite a los bancos generar mas certificados de oro y plata. Básicamente 'crear' mas oro ficticiamente. Pero que pasa si todos los que tienen papelitos deciden sacar su oro al mismo tiempo. El banco en este momento no puede dar el oro a cada poseedor de un certificado.

El siguiente paso en la evolución de los bancos y el dinero es el FIAT. Dinero que no esta respaldado por 'nada' pero sirve para pagar impuestos. Dinero respaldado por un gobierno. Es la razón principal, en mi opinión, por la cual el concepto del dinero no se enseña mas. Si la gente en general supiera como funciona el dinero habría una u otra rebelión este mundo.

La cuestión importante es que el dinero FIAT esta controlado por el banco central de cada país y es el responsable de la emisión de dinero en el país. Es el banco central quien decide emitir mas dinero que supuestamente tiene que circular por todo el sistema económico del país pero que en ultimo termino causa un exceso de papeles en el sistema quitándole el valor a todos los papeles en existencia.

Y aquí esta la primera razón por la existencia de Bitcoin. La emisión monetaria es sabida desde ahora y va a llegar a un tope de 21 millón de bitcoins (BTC). No hay ningún gobierno que la controla por ende ningún gobierno tiene el poder de emitir BTC para satisfacer sus necesidades.

La segunda razón es la naturaleza global de BTC. Para que alguien controle bitcoin tendría que controlar todos los mineros del mundo. Es posible, pero es involucraría una conspiración tan grande que en este momento la podemos calificar de imposible.

La tercera razón es la distribución de los mineros, los entes responsable por la creación de los bloques. Distribuidos por todo el mundo y muy difícil (no imposible). Esta y la segunda razón son similares pero referencian el tema que nadie esta en control de la minería tampoco. Para mas datos ver: https://www.blockchain.com/pools